#!/bin/sh
# jvmtop - java monitoring for the command-line 
# launch script
#
# author: Markus Kolb
# 
DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"

# if the last arg is a pid, use that procs java for java_home
for last_param; do true; done
if [ ! -z "$last_param" ] && [ -f "/proc/${last_param}/exe" ] ; then
  parsed_command=`readlink -f /proc/${last_param}/exe | perl -lne 'print $1 if /(.*?)(\/jre)?\/bin\/java$/'`
  if [ ! -z "$parsed_command" ] ; then
    JAVA_HOME=$parsed_command
  fi
fi

if [ -z "$JAVA_HOME" ] ; then
  JAVA_HOME=`readlink -f \`which java 2>/dev/null\` 2>/dev/null | sed 's/\/bin\/java//'`
fi

TOOLSJAR="$JAVA_HOME/lib/tools.jar"

if [ ! -f "$TOOLSJAR" ] ; then
  echo "$JAVA_HOME seems to be no JDK!" >&2
  exit 1
fi

"$JAVA_HOME"/bin/java $JAVA_OPTS -cp "$DIR/jvmtop.jar:$TOOLSJAR" \
com.jvmtop.JvmTop "$@"
exit $?
